spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000ms
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 5
          min-idle: 2
          max-wait: 3000ms
